### ISSUE TITLE
AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#31]
When starting the flagging procedure, the following problem appears on Mac:

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/figure.py", line 1165, in draw
    self.canvas.draw_event(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1809, in draw_event
    self.callbacks.process(s, event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/widgets.py", line 1176, in update_background
    self.background = self.canvas.copy_from_bbox(self.ax.bbox)
AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'
```

**Comment by leonro** [comment]
Tried to reproduce this error with version 0.3.95 on a Mac OS 10.12. Failed, however... Eventually this bug was already solved with one of the earlier fixes. Will close this issue with 1619752ff2d9b37f67a348f1b95eccc74a51848c .
