### ISSUE TITLE
dialogclasses.py: list index out of range

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#36]
Clicking Options -> Basic Installation Parameters on Mac results in:
~~~
Traceback (most recent call last):
  File "/path/to/magpy/gui/magpy_gui.py", line 1904, in OnOptionsInit
    dlg = OptionsInitDialog(None, title='Options: Parameter specifications',options=self.options)
  File "/path/to/magpy/gui/dialogclasses.py", line 559, in __init__
    self.createControls()
  File "/path/to/magpy/gui/dialogclasses.py", line 592, in createControls
    self.bookmarksComboBox = wx.ComboBox(self, choices=self.options.get('bookmarks',[]),size=(160,30),style=wx.CB_DROPDOWN, value=self.options.get('bookmarks',[])[0])
IndexError: list index out of range
~~~

**Comment by leonro** [comment]
Finished with 6a3d4ab11080af05f7b77b923108c07d41945300.
Closing #36
