### ISSUE TITLE
Failing CDF-format detection (finds USBLOG instead) on Windows

### ISSUE THREAD

**Issue by bairaelyn** [geomagpy/magpy#54]
Called through the GUI on Windows, the read() script has problems detecting CDF format files correctly. The files are somehow detected as USBLOG, which leads to an error being thrown by readUSBLOG(...). This mostly seems to be true for CDF files produced after March 2016.

**Comment by leonro** [comment]
This problem requires an update of the NASA CDF library. Only the new library supports CDF compression. Closing #54

**Comment by mojca** [comment]
I happened to see this ticket after downloading some files from the intermagnet website. The files have the filename `CCCYYYYMMDDdmin.min.gz` (`CCC` is observatory code, followed by the date). Opening that file fails with
~~~
Sorting: key t1 has the wrong length - replacing row with NaNs
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magpy/gui/magpy_gui.py", line 1607, in OnOpenFile
    tmp = read(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magpy/stream.py", line 9713, in read
    stp = _read(filename, dataformat, headonly, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magpy/stream.py", line 9787, in _read
    stream = readFormat(filename, format_type, headonly=headonly, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magpy/lib/magpy_formats.py", line 299, in readFormat
    return readUSBLOG(filename, headonly, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magpy/lib/format_wic.py", line 418, in readUSBLOG
    for elem in csvReader:
_csv.Error: line contains NULL byte
Sorting: key t1 has the wrong length - replacing row with NaNs
~~~
I guess I have to open another ticket, I just wanted to let you know that CDF might not be the only place with the above mentioned failure.
