### ISSUE TITLE
Hangup-during initilisation of datastream

### ISSUE THREAD

**Issue by sparky-corona** [geomagpy/magpy#76]
geomagpy **v0.3.96**

Error Message while loading MARCOS Datastream of GP203NS Sensor data:

---------------------
Running ...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/magpy/gui/magpy_gui.py", line 5420, in onStartMonitorButton
    self.plot_p.startMARCOSMonitor()
  File "/usr/local/lib/python2.7/dist-packages/magpy/gui/magpy_gui.py", line 445, in startMARCOSMonitor
    self.array[idx] = [datetime.strptime(el[0],"%Y-%m-%d %H:%M:%S.%f") for el in li]
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 0
---------------------

GUI no reaction. have to use kill -9 to stop process xmagpy.

**Comment by leonro** [comment]
Done with 6bc6568326a217744ab41f1cfa759ab876004b12
