### ISSUE TITLE
Attribute Error: 'numpy.float64' object has no attribute 'toordinal'

### ISSUE THREAD

**Issue by sparky-corona** [geomagpy/magpy#78]
geomagpy v0.3.96
While loading bin / raw data from GP20S3 data file:
error message: Attribute Error: 'numpy.float64' object has no attribute 'toordinal'

---------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/magpy/gui/magpy_gui.py", line 5449, in onStopMonitorButton
    self.stream = self._monitor2stream(self.plot_p.array,db=self.db,dataid=dataid)
  File "/usr/local/lib/python2.7/dist-packages/magpy/gui/magpy_gui.py", line 5439, in _monitor2stream
    array[0] = date2num(array[0])
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 260, in date2num
    else: return np.asarray([_to_ordinalf(val) for val in d])
  File "/usr/lib/pymodules/python2.7/matplotlib/dates.py", line 189, in _to_ordinalf
    base =  float(dt.toordinal())
AttributeError: 'numpy.float64' object has no attribute 'toordinal'

---------------------------

GUI keeps on working.

**Comment by leonro** [comment]
Done with 6bc6568326a217744ab41f1cfa759ab876004b12
