### ISSUE TITLE
MARCOS monitor: Live stream

### ISSUE THREAD

**Issue by leonro** [geomagpy/magpy#92]
xmagpy
Trying to access initialization file: /home/niko/.magpyguiini
... success
connected to database 'cobsdb' (MYSQL Version 5.5.58-0ubuntu0.14.04.1) - size in GB: not determined
Traceback (most recent call last):
  File "/home/niko/Software/Programming/anaconda2/lib/python2.7/site-packages/magpy/gui/magpy_gui.py", line 6040, in onStartMonitorButton
    self.plot_p.startMARCOSMonitor()
  File "/home/niko/Software/Programming/anaconda2/lib/python2.7/site-packages/magpy/gui/magpy_gui.py", line 387, in startMARCOSMonitor
    self.array[idx] = [datetime.strptime(el[0],"%Y-%m-%d %H:%M:%S.%f") for el in li]
  File "/home/niko/Software/Programming/anaconda2/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2019-01-17 08:42:32' does not match format '%Y-%m-%d %H:%M:%S.%f'
Traceback (most recent call last):
  File "/home/niko/Software/Programming/anaconda2/lib/python2.7/site-packages/magpy/gui/magpy_gui.py", line 6075, in onStopMonitorButton
    self.stream.header['StationID'] = self.plot_p.datavars[15]
KeyError: 15

**Comment by leonro** [comment]
Fixed in f872248466bfb6e061f834f5a07baf8b42fb1da1
